# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'Any CPU'
  buildConfiguration: 'Release'

steps:

- task: DotNetCoreCLI@2
  inputs:
    azureSubscription: 'Pay-As-You-Go(886ab17f-b344-4db5-9b16-d7768b64f994)'
    command: 'publish'
    publishWebProjects: false
    projects: '**/DummyAPI.csproj'
    arguments: '--configuration Release --output $(Build.ArtifactStagingDirectory)/DummyAPI'


- task: ArchiveFiles@2
  inputs:
    rootFolderOrFile: '$(Build.ArtifactStagingDirectory)/DummyAPI'
    includeRootFolder: true
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/DummyAPI.zip'
    replaceExistingArchive: true


- task: AzureWebApp@1
  inputs:
    azureSubscription: 'Pay-As-You-Go(886ab17f-b344-4db5-9b16-d7768b64f994)'
    appType: 'webApp'
    appName: 'azurewebapplearning'
    package: '$(Build.ArtifactStagingDirectory)/DummyAPI.zip'
    deploymentMethod: 'auto'